apiVersion: v2
name: k8s-infra
description: Helm chart for collecting metrics and logs in K8s
type: application
version: 0.15.0
appVersion: "0.139.0"
home: https://o11y.hanzo.ai
icon: https://o11y.hanzo.ai/img/Hanzo O11yLogo-orange.svg
keywords:
  - Hanzo O11y
  - OpenTelemetry
  - apm
  - monitoring
  - logs
sources:
  - https://github.com/o11y/charts
  - https://github.com/open-telemetry/opentelemetry-collector-contrib
maintainers:
  - name: Hanzo O11y
    email: hello@o11y.hanzo.ai
    url: https://o11y.hanzo.ai
  - name: prashant-shahi
    email: prashant@o11y.hanzo.ai
    url: https://prashantshahi.dev
