apiVersion: v2
name: o11y
version: 0.115.0
appVersion: "v0.115.0"
description: Hanzo O11y Observability Platform Helm Chart
type: application
home: https://o11y.hanzo.ai/
icon: https://o11y.hanzo.ai/img/Hanzo O11yLogo-orange.svg
keywords:
  - Hanzo O11y
  - opentelemetry
  - apm
  - monitoring
  - distributed tracing
  - distributed logging
sources:
  - https://github.com/o11y/charts
  - https://github.com/ghcr.io/hanzoai/o11y
  - https://github.com/ghcr.io/hanzoai/otel-collector
dependencies:
  - name: clickhouse
    repository: https://charts.o11y.hanzo.ai
    condition: clickhouse.enabled
    version: 24.1.18
  - name: o11y-otel-gateway
    repository: https://charts.o11y.hanzo.ai
    condition: o11y-otel-gateway.enabled
    version: 0.0.4
  - name: redpanda
    repository: https://charts.redpanda.com
    condition: redpanda.enabled
    version: 5.10.2
  - name: postgresql
    repository: https://charts.o11y.hanzo.ai
    condition: postgresql.enabled
    version: 0.0.2
maintainers:
  - name: Hanzo O11y
    email: hello@o11y.hanzo.ai
    url: https://o11y.hanzo.ai
  - name: prashant-shahi
    email: prashant@o11y.hanzo.ai
    url: https://prashantshahi.dev
