apiVersion: v2
name: o11y-otel-gateway
description: A Helm chart for deploying Hanzo O11y Opentelemetry Gateway
type: application
version: 0.0.4
appVersion: "v0.0.16"
home: https://o11y.hanzo.ai/
icon: https://o11y.hanzo.ai/img/Hanzo O11yLogo-orange.svg
maintainers:
  - name: Hanzo O11y
    email: devops@o11y.hanzo.ai
    url: https://o11y.hanzo.ai

