apiVersion: v2
name: postgresql
version: 0.0.2
appVersion: 15.0.0
description: A Helm Chart for PostgreSQL
type: application
home: https://o11y.hanzo.ai/
icon: https://wiki.postgresql.org/wiki/File:PostgreSQL_logo.3colors.svg
sources:
  - https://github.com/o11y/charts
  - https://github.com/postgres/postgres
maintainers:
  - name: Hanzo O11y
    email: hello@o11y.hanzo.ai
    url: https://o11y.hanzo.ai
