apiVersion: v2
name: clickhouse
description: A Helm chart for ClickHouse
type: application
version: 24.1.18
appVersion: "24.1.2"
icon: https://github.com/ClickHouse/clickhouse-docs/raw/84f38d893eb7e561c7296279d7953b6a508ec413/static/img/clickhouse-logo.svg
sources:
  - https://github.com/Hanzo O11y/charts
  - https://github.com/ClickHouse/ClickHouse
dependencies:
  - name: zookeeper
    repository: "file://../zookeeper"
    version: 0.0.1
    condition: zookeeper.enabled
maintainers:
  - name: Hanzo O11y
    email: hello@o11y.hanzo.ai
    url: https://o11y.hanzo.ai
  - name: prashant-shahi
    email: prashant@o11y.hanzo.ai
    url: https://prashantshahi.dev
