apiVersion: v1
kind: Service
metadata:
  name: {{ include "o11y.fullname" . }}
  labels:
    {{- include "o11y.labels" . | nindent 4 }}
{{- with .Values.o11y.service }}
{{- if .labels }}
    {{- toYaml .labels | nindent 4 }}
{{- end }}
{{- if .annotations }}
  annotations:
    {{- toYaml .annotations | nindent 4 }}
{{- end }}
spec:
  type: {{ .type }}
  ports:
    - name: http
      port: {{ .port }}
      {{- include "o11y.service.ifClusterIP" .type | indent 6 }}
      protocol: TCP
      targetPort: http
      {{- if (and (eq .type "NodePort") .nodePort) }}
      nodePort: {{ .nodePort }}
      {{- end }}
    - name: http-internal
      port: {{ .internalPort }}
      {{- include "o11y.service.ifClusterIP" .type | indent 6 }}
      protocol: TCP
      targetPort: http-internal
      {{- if (and (eq .type "NodePort") .internalNodePort) }}
      nodePort: {{ .internalNodePort }}
      {{- end }}
    - name: opamp-internal
      port: {{ .opampPort }}
      {{- include "o11y.service.ifClusterIP" .type | indent 6 }}
      protocol: TCP
      targetPort: opamp-internal
      {{- if (and (eq .type "NodePort") .opampInternalNodePort) }}
      nodePort: {{ .opampInternalNodePort }}
      {{- end }}
{{- end }}
  selector:
    {{- include "o11y.selectorLabels" . | nindent 4 }}
