apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: {{ include "o11y.fullname" . }}
  labels:
    {{- include "o11y.labels" . | nindent 4 }}
  {{- if .Values.o11y.annotations }}
  annotations:
    {{- toYaml .Values.o11y.annotations | nindent 4 }}
  {{- end }}
spec:
  serviceName: {{ include "o11y.fullname" . }}
  replicas: {{ .Values.o11y.replicaCount }}
  selector:
    matchLabels:
      {{- include "o11y.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      {{- if .Values.o11y.podAnnotations }}
      annotations:
        {{- toYaml .Values.o11y.podAnnotations | nindent 8 }}
      {{- end }}
      labels:
        {{- include "o11y.selectorLabels" . | nindent 8 }}
    spec:
      {{- with .Values.o11y.imagePullSecrets }}
      imagePullSecrets:
      {{- range . }}
        - name: {{ . | quote }}
      {{- end }}
      {{- end }}
      serviceAccountName: {{ include "o11y.serviceAccountName" . }}
      priorityClassName: {{ .Values.o11y.priorityClassName | quote }}
      {{- with .Values.o11y.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.o11y.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.o11y.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.o11y.topologySpreadConstraints }}
      topologySpreadConstraints:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      securityContext:
        {{- toYaml .Values.o11y.podSecurityContext | nindent 8 }}
      containers:
        - name: o11y
          securityContext:
            {{- toYaml .Values.o11y.securityContext | nindent 12 }}
          image: {{ template "o11y.image" . }}
          imagePullPolicy: {{ .Values.o11y.image.pullPolicy }}
          args:
            {{- range .Values.o11y.additionalArgs }}
            - {{ . | quote }}
            {{- end }}
          ports:
            - name: http
              containerPort: {{ default 8080  .Values.o11y.service.port }}
              protocol: TCP
            - name: http-internal
              containerPort: {{ default 8085 .Values.o11y.service.internalPort }}
              protocol: TCP
            - name: opamp-internal
              containerPort: {{ default 4320 .Values.o11y.service.opampPort }}
              protocol: TCP
          env:
            {{- include "snippet.clickhouse-credentials" . | nindent 12 }}
            {{- include "o11y.env" . | nindent 12 }}
          {{- if .Values.o11y.livenessProbe.enabled }}
          livenessProbe:
            httpGet:
              port: {{ .Values.o11y.livenessProbe.port }}
              path: {{ .Values.o11y.livenessProbe.path }}
            initialDelaySeconds: {{ .Values.o11y.livenessProbe.initialDelaySeconds }}
            periodSeconds: {{ .Values.o11y.livenessProbe.periodSeconds }}
            timeoutSeconds: {{ .Values.o11y.livenessProbe.timeoutSeconds }}
            successThreshold: {{ .Values.o11y.livenessProbe.successThreshold }}
            failureThreshold: {{ .Values.o11y.livenessProbe.failureThreshold }}
          {{- else if .Values.o11y.customLivenessProbe }}
          livenessProbe: {{- toYaml .Values.o11y.customLivenessProbe | nindent 12 }}
          {{- end }}
          {{- if .Values.o11y.readinessProbe.enabled }}
          readinessProbe:
            httpGet:
              port: {{ .Values.o11y.readinessProbe.port }}
              path: {{ .Values.o11y.readinessProbe.path }}
            initialDelaySeconds: {{ .Values.o11y.readinessProbe.initialDelaySeconds }}
            periodSeconds: {{ .Values.o11y.readinessProbe.periodSeconds }}
            timeoutSeconds: {{ .Values.o11y.readinessProbe.timeoutSeconds }}
            successThreshold: {{ .Values.o11y.readinessProbe.successThreshold }}
            failureThreshold: {{ .Values.o11y.readinessProbe.failureThreshold }}
          {{- else if .Values.o11y.customReadinessProbe }}
          readinessProbe: {{- toYaml .Values.o11y.customReadinessProbe | nindent 12 }}
          {{- end }}
          volumeMounts:
          {{- if not .Values.postgresql.enabled }}
          {{- if .Values.o11y.persistence.enabled }}
          {{- if .Values.o11y.persistence.existingClaim }}
            - name: o11y-db-existing-claim
          {{- else }}
            - name: o11y-db
          {{- end }}
          {{- else }}
            - name: o11y-db-volume
          {{- end }}
              mountPath: /var/lib/o11y/
          {{- end}}
          {{- if .Values.o11y.additionalVolumeMounts }}
            {{- toYaml .Values.o11y.additionalVolumeMounts | nindent 12 }}
          {{- end }}
          resources:
            {{- toYaml .Values.o11y.resources | nindent 12 }}
      volumes:
        - name: dashboards
          emptyDir: {}
        {{- if and (not .Values.o11y.persistence.enabled) (not .Values.postgresql.enabled )}}
        - name: o11y-db-volume
          emptyDir: {}
        {{- else if and .Values.o11y.persistence.existingClaim (not .Values.postgresql.enabled )}}
        - name: o11y-db-existing-claim
          persistentVolumeClaim:
            claimName: {{ .Values.o11y.persistence.existingClaim }}
        {{- end }}
        {{- if .Values.o11y.additionalVolumes }}
          {{- toYaml .Values.o11y.additionalVolumes | nindent 8 }}
        {{- end }}

{{- if and (.Values.o11y.persistence.enabled) (not .Values.o11y.persistence.existingClaim) ( not .Values.postgresql.enabled )}}
  volumeClaimTemplates:
    - metadata:
        name: o11y-db
      spec:
        accessModes:
          {{- toYaml .Values.o11y.persistence.accessModes | nindent 10 }}
        resources:
          requests:
            storage: {{ .Values.o11y.persistence.size }}
      {{- $storageClass := default .Values.o11y.persistence.storageClass .Values.global.storageClass -}}
      {{- if $storageClass -}}
      {{- if (eq "-" $storageClass) }}
        storageClassName: ""
      {{- else }}
        storageClassName: {{ $storageClass }}
      {{- end }}
      {{- end }}
{{- end }}
